seed: 0
# could go lower, but 1 second per request to avoid spamming
delay: 1
model: gpt-4-vision-preview
max_tokens: 512
temperature: 1.0
top_p: 0.7
system_prompt: >-
  You are an expert linguistic assistant.
  Frames of communication select particular aspects of an issue and make them salient in communicating a message.
  Frames of communication are ubiquitous in social media discourse and can impact how people understand issues and, more importantly, how they form their opinions.
  You will be tasked with identifying and articulating misogyny framings on the following images.
  You should discuss your reasoning in detail, thinking step-by-step.
  Make sure to explain how the image and the text in the image together contribute to the frame.
  Your final answer should be provided on a new line, and you should articulate the frames succinctly if the input image evokes any frames.
